#!/usr/bin/env python3
"""
异构链路（pg / mysql / mongo）断点续传 + 故障注入测试的引擎适配层。

为 pg2pg / mysql2pg / pg2mysql / mongo2mongo 提供统一抽象：
  - 源端：建表(集合) + 播种存量 + 后台持续写入(INSERT/UPDATE/DELETE)。
  - 任意端：抽取「规范化行」(id, grp, val, payload, n) → 计算与引擎无关、顺序无关、
    对增删改敏感的指纹 (count, xor)，用于跨异构数据库比对一致性。

规范化行的类型在各引擎间必须一致：id/grp/n 为 int（n 可空），val/payload 为 str（可空）。
只取这几列入指纹（不含时间戳/浮点，规避跨库时区/精度差异）。表名统一 fi_load / 集合 fi_load。
"""
import random
import threading
import time
import zlib

import mysql.connector
import psycopg2
import pymongo

TABLE = "fi_load"


# ----------------------------------------------------------------- 指纹（跨引擎）
def canon_key(row):
    """规范化一行 → 稳定字符串。row = (id, grp, val, payload, n)。"""
    rid, grp, val, payload, n = row
    return "|".join([
        str(int(rid)),
        str(int(grp)),
        "\x00" if val is None else str(val),
        "\x00" if payload is None else str(payload),
        "\x00" if n is None else str(int(n)),
    ])


def fp_from_rows(rows):
    """顺序无关(XOR)、对每列敏感、天然按 id 去重的整表指纹。"""
    x = 0
    for r in rows:
        x ^= zlib.crc32(canon_key(r).encode("utf-8"))
    return (len(rows), x)


# ----------------------------------------------------------------- SQL 引擎（mysql/pg）
class SqlEndpoint:
    def __init__(self, spec):
        self.kind = spec["kind"]           # "mysql" | "pg"
        self.host = spec["host"]
        self.port = spec["port"]
        self.user = spec["user"]
        self.password = spec["password"]
        self.db = spec["db"]
        # PG 目标 schema：mysql→pg 时同步把表落在「源库名」schema 下（非 public）；pg→pg 落 public。
        # 源端 PG 表建在 public。用 search_path 让非限定表名解析到正确 schema。
        self.schema = spec.get("schema", "public")

    # -- 连接 --
    def _conn(self, db=None, autocommit=True):
        if self.kind == "mysql":
            c = mysql.connector.connect(host=self.host, port=self.port, user=self.user,
                                        password=self.password, database=db, use_pure=True,
                                        autocommit=autocommit)
            cur = c.cursor()
            cur.execute("SET time_zone='+00:00'")
            cur.close()
            return c
        else:
            c = psycopg2.connect(host=self.host, port=self.port, user=self.user,
                                 password=self.password, dbname=db or "postgres")
            c.autocommit = autocommit
            cur = c.cursor()
            cur.execute(f'SET search_path TO "{self.schema}", public')
            cur.close()
            return c

    def _maint_db(self):
        # 用于 DROP/CREATE DATABASE 的维护连接库（不能连在要删的库上）
        return "mysql" if self.kind == "mysql" else "postgres"

    # -- 源端：干净重建 + 播种 --
    def reset_source(self):
        self._drop_create_db()
        self._create_table()

    def reset_target(self):
        # 目标表由同步引擎按源 schema 自动创建，这里只保证目标库为空且存在
        self._drop_create_db()

    def _drop_create_db(self):
        if self.kind == "mysql":
            c = self._conn(self._maint_db())
            cur = c.cursor()
            cur.execute(f"DROP DATABASE IF EXISTS `{self.db}`")
            cur.execute(f"CREATE DATABASE `{self.db}` DEFAULT CHARACTER SET utf8mb4")
            cur.close(); c.close()
        else:
            c = self._conn(self._maint_db())
            cur = c.cursor()
            # 先删该库上遗留的逻辑复制槽（否则 DROP DATABASE 会被占用/报错）
            cur.execute("SELECT slot_name FROM pg_replication_slots WHERE database=%s", (self.db,))
            for (sn,) in cur.fetchall():
                try:
                    cur.execute("SELECT pg_drop_replication_slot(%s)", (sn,))
                except Exception:
                    pass
            # 断开该库上的其它连接
            cur.execute("SELECT pg_terminate_backend(pid) FROM pg_stat_activity "
                        "WHERE datname=%s AND pid<>pg_backend_pid()", (self.db,))
            cur.execute(f'DROP DATABASE IF EXISTS "{self.db}"')
            cur.execute(f'CREATE DATABASE "{self.db}"')
            cur.close(); c.close()

    def _create_table(self):
        c = self._conn(self.db)
        cur = c.cursor()
        if self.kind == "mysql":
            cur.execute(f"""
                CREATE TABLE `{TABLE}` (
                  `id` BIGINT NOT NULL AUTO_INCREMENT,
                  `grp` INT NOT NULL,
                  `val` VARCHAR(128),
                  `payload` VARCHAR(512),
                  `n` BIGINT,
                  PRIMARY KEY (`id`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4""")
        else:
            cur.execute(f"""
                CREATE TABLE {TABLE} (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  grp INT NOT NULL,
                  val VARCHAR(128),
                  payload VARCHAR(512),
                  n BIGINT
                )""")
        cur.close(); c.close()

    def seed(self, rows):
        c = self._conn(self.db)
        cur = c.cursor()
        ins = f"INSERT INTO {self._t()} (grp,val,payload,n) VALUES (%s,%s,%s,%s)"
        # PG 的 executemany 是逐条往返，播种 10 万行以上会慢到分钟级——用 execute_values
        # 单语句多值批量插入（同样的行内容，只是灌数快 1~2 个数量级）。
        if self.kind == "pg":
            from psycopg2.extras import execute_values
            ins_pg = f"INSERT INTO {self._t()} (grp,val,payload,n) VALUES %s"
            batch = []
            for i in range(rows):
                batch.append((i % 100, f"seed-{i}", "x" * 200, i))
                if len(batch) >= 5000:
                    execute_values(cur, ins_pg, batch, page_size=5000); batch = []
            if batch:
                execute_values(cur, ins_pg, batch, page_size=5000)
            c.commit()
            cur.close(); c.close()
            return
        batch = []
        for i in range(rows):
            batch.append((i % 100, f"seed-{i}", "x" * 200, i))
            if len(batch) >= 1000:
                cur.executemany(ins, batch); batch = []
        if batch:
            cur.executemany(ins, batch)
        cur.close(); c.close()

    def _t(self):
        return f"`{TABLE}`" if self.kind == "mysql" else TABLE

    # -- 指纹 --
    def fetch_rows(self):
        c = self._conn(self.db)
        cur = c.cursor()
        cur.execute(f"SELECT id,grp,val,payload,n FROM {self._t()}")
        rows = cur.fetchall()
        cur.close(); c.close()
        return [(r[0], r[1], r[2], r[3], r[4]) for r in rows]

    def fingerprint(self):
        return fp_from_rows(self.fetch_rows())

    def count(self):
        c = self._conn(self.db)
        cur = c.cursor()
        try:
            cur.execute(f"SELECT COUNT(*) FROM {self._t()}")
            return cur.fetchone()[0]
        except Exception:
            return 0
        finally:
            cur.close(); c.close()

    def make_writer(self, interval):
        return SqlWriter(self, interval)


class SqlWriter(threading.Thread):
    """源端持续写入：INSERT 为主，穿插 UPDATE/DELETE。以本地跟踪的 id 做增改删，跨引擎可移植。"""
    def __init__(self, ep, interval):
        super().__init__(daemon=True)
        self.ep = ep
        self.interval = interval
        self.stop = threading.Event()
        self.inserts = self.updates = self.deletes = 0
        self.error = None
        self.ids = []

    def run(self):
        try:
            c = self.ep._conn(self.ep.db)
            cur = c.cursor()
            t = self.ep._t()
            seq = 0
            while not self.stop.is_set():
                seq += 1
                if self.ep.kind == "mysql":
                    cur.execute(f"INSERT INTO {t} (grp,val,payload,n) VALUES (%s,%s,%s,%s)",
                                (seq % 100, f"live-{seq}", "y" * 200, 1000000 + seq))
                    self.ids.append(cur.lastrowid)
                else:
                    cur.execute(f"INSERT INTO {t} (grp,val,payload,n) VALUES (%s,%s,%s,%s) RETURNING id",
                                (seq % 100, f"live-{seq}", "y" * 200, 1000000 + seq))
                    self.ids.append(cur.fetchone()[0])
                    c.commit()
                self.inserts += 1
                if seq % 5 == 0 and self.ids:
                    rid = random.choice(self.ids)
                    cur.execute(f"UPDATE {t} SET val=%s, n=n+1 WHERE id=%s", (f"upd-{seq}", rid))
                    if self.ep.kind == "pg":
                        c.commit()
                    self.updates += 1
                if seq % 23 == 0 and len(self.ids) > 10:
                    rid = self.ids.pop(0)
                    cur.execute(f"DELETE FROM {t} WHERE id=%s", (rid,))
                    if self.ep.kind == "pg":
                        c.commit()
                    self.deletes += 1
                time.sleep(self.interval)
            cur.close(); c.close()
        except Exception as e:  # noqa: BLE001
            self.error = e


# ----------------------------------------------------------------- Mongo 引擎
class MongoEndpoint:
    def __init__(self, spec):
        self.kind = "mongo"
        self.host = spec["host"]
        self.port = spec["port"]
        self.user = spec["user"]
        self.password = spec["password"]
        self.db = spec["db"]

    def _client(self):
        uri = (f"mongodb://{self.user}:{self.password}@{self.host}:{self.port}"
               f"/?authSource=admin&directConnection=true")
        return pymongo.MongoClient(uri)

    def reset_source(self):
        cl = self._client()
        cl.drop_database(self.db)
        # 预建集合（可选）；插入会自动建
        cl[self.db].create_collection(TABLE)
        cl.close()

    def reset_target(self):
        cl = self._client()
        cl.drop_database(self.db)
        cl.close()

    def seed(self, rows):
        cl = self._client()
        coll = cl[self.db][TABLE]
        batch = []
        for i in range(rows):
            batch.append({"_id": i + 1, "grp": i % 100, "val": f"seed-{i}",
                          "payload": "x" * 200, "n": i})
            if len(batch) >= 1000:
                coll.insert_many(batch); batch = []
        if batch:
            coll.insert_many(batch)
        cl.close()

    def fetch_rows(self):
        cl = self._client()
        coll = cl[self.db][TABLE]
        rows = []
        for d in coll.find({}, {"_id": 1, "grp": 1, "val": 1, "payload": 1, "n": 1}):
            rows.append((d["_id"], d.get("grp"), d.get("val"), d.get("payload"), d.get("n")))
        cl.close()
        return rows

    def fingerprint(self):
        return fp_from_rows(self.fetch_rows())

    def count(self):
        cl = self._client()
        try:
            return cl[self.db][TABLE].count_documents({})
        except Exception:
            return 0
        finally:
            cl.close()

    def make_writer(self, interval):
        return MongoWriter(self, interval)


class MongoWriter(threading.Thread):
    def __init__(self, ep, interval):
        super().__init__(daemon=True)
        self.ep = ep
        self.interval = interval
        self.stop = threading.Event()
        self.inserts = self.updates = self.deletes = 0
        self.error = None
        self.ids = []
        self._next = None

    def run(self):
        try:
            cl = self.ep._client()
            coll = cl[self.ep.db][TABLE]
            mx = coll.find_one(sort=[("_id", -1)])
            self._next = (mx["_id"] + 1) if mx else 1
            seq = 0
            while not self.stop.is_set():
                seq += 1
                _id = self._next; self._next += 1
                coll.insert_one({"_id": _id, "grp": seq % 100, "val": f"live-{seq}",
                                 "payload": "y" * 200, "n": 1000000 + seq})
                self.ids.append(_id)
                self.inserts += 1
                if seq % 5 == 0 and self.ids:
                    rid = random.choice(self.ids)
                    coll.update_one({"_id": rid}, {"$set": {"val": f"upd-{seq}"}, "$inc": {"n": 1}})
                    self.updates += 1
                if seq % 23 == 0 and len(self.ids) > 10:
                    rid = self.ids.pop(0)
                    coll.delete_one({"_id": rid})
                    self.deletes += 1
                time.sleep(self.interval)
            cl.close()
        except Exception as e:  # noqa: BLE001
            self.error = e


def make_endpoint(spec):
    return MongoEndpoint(spec) if spec["kind"] == "mongo" else SqlEndpoint(spec)


# ----------------------------------------------------------------- 链路定义
PGH = dict(host="127.0.0.1", port=5432, user="app_user", password="userpassword")
MYH = dict(host="127.0.0.1", port=33306, user="root", password="rootpassword")

LINKS = {
    "pg2pg": dict(
        source_type="postgresql", target_type="postgresql",
        source={**PGH, "kind": "pg", "db": "fi_src_pgpg"},
        target={**PGH, "kind": "pg", "db": "fi_tgt_pgpg"},
        src_conn="postgresql://app_user:userpassword@127.0.0.1:5432/fi_src_pgpg",
        tgt_conn="postgresql://app_user:userpassword@127.0.0.1:5432/fi_tgt_pgpg",
        sync_objects='{"fi_src_pgpg": ["public.fi_load"]}',
        engines=["capture", "extract", "increment"],
    ),
    "mysql2pg": dict(
        source_type="mysql", target_type="postgresql",
        source={**MYH, "kind": "mysql", "db": "fi_src_myp"},
        # mysql→pg：同步把表落在「源库名」schema（fi_src_myp）下，非 public
        target={**PGH, "kind": "pg", "db": "fi_tgt_myp", "schema": "fi_src_myp"},
        src_conn="mysql://root:rootpassword@127.0.0.1:33306",
        tgt_conn="postgresql://app_user:userpassword@127.0.0.1:5432/fi_tgt_myp",
        sync_objects='{"fi_src_myp": {"tables": ["fi_load"]}}',
        engines=["capture", "extract", "increment"],
    ),
    "pg2mysql": dict(
        source_type="postgresql", target_type="mysql",
        source={**PGH, "kind": "pg", "db": "fi_src_pgm"},
        target={**MYH, "kind": "mysql", "db": "fi_tgt_pgm"},
        src_conn="postgresql://app_user:userpassword@127.0.0.1:5432/fi_src_pgm",
        tgt_conn="mysql://root:rootpassword@127.0.0.1:33306",
        sync_objects='{"fi_src_pgm": ["public.fi_load"]}',
        engines=["capture", "extract", "increment"],
    ),
    # 注意：migration-mongo 是「同名命名空间镜像」——源库 fi_mgo → 目标同名库 fi_mgo（忽略
    # targetDbName），源/目标为不同 mongo 实例（27117/27118）故不冲突。因此 target.db 必须等于
    # source.db，否则会去错误的库上比对到 0 文档（这是引擎的既定行为，非缺陷）。
    "mongo2mongo": dict(
        source_type="mongodb", target_type="mongodb",
        source=dict(kind="mongo", host="localhost", port=27117, user="root",
                    password="rootpassword", db="fi_mgo"),
        target=dict(kind="mongo", host="localhost", port=27118, user="root",
                    password="rootpassword", db="fi_mgo"),
        src_conn="mongodb://root:rootpassword@localhost:27117",
        tgt_conn="mongodb://root:rootpassword@localhost:27118",
        sync_objects='{"fi_mgo": ["fi_load"]}',
        engines=["mongo"],
    ),
}
